app = "currency-system-app"  # اسم فريد لازم يكون غير مستخدم

primary_region = "fra"  # ممكن تغيرها حسب أقرب مكان ليك (ams, lhr, sin, etc)

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
